#!/usr/bin/env python3
""" A minimal version of grep, with some limited options """

import argparse
import re
import sys
import os


def is_valid_regex(regex_str):
    """ Checks if string is valid regex """
    try:
        re.compile(regex_str)
        is_valid = True
    except re.error:
        is_valid = False

    return is_valid


def parse_cmd_args():
    """ Parse command-line arguments """

    parser = argparse.ArgumentParser(prog="mini-grep",
                                     description="Minimal version of grep",
                                     add_help=True)

    # Optional argument to make the script quieter. False by default
    parser.add_argument("-q", dest="quiet", help="(q)uiet only outputs lines\
                         but omits the matching line numbers",
                        action='store_true', required=False)

    # Required regex pattern argument
    parser.add_argument("-e", dest="PATTERN",
                        help="valid regex pattern to search for", type=str,
                        required=True)

    # FILE variadic argument
    parser.add_argument("FILE", action='store', type=str, nargs='*')
    args = parser.parse_args()

    return args


def enum_and_match(file, regex_pattern, stdin_ln_list, quiet_flag):
    """ Enumerate stdin input list or a file's lines """

    # If file was given
    if file:
        with open(file, encoding='utf-8') as f:
            enum_iter = f.readlines()

    # Else if stdin input was given
    elif stdin_ln_list:
        enum_iter = stdin_ln_list

    # If no file and no stdin input was given, fatally exit
    else:
        sys.exit("ERROR: file list or stdin input is invalid!")

    # Enumerate the file or stdin input
    for i, line in enumerate(enum_iter):

        # Strip newlines for cosmetic reasons in output
        line_stripped = line.rstrip('\n')

        # For each matching line, print it
        for _ in re.finditer(regex_pattern, line):

            # If quiet output was requested, print only the matching line
            if quiet_flag:
                print(f"{line_stripped}")

            # If quiet output wasn't requested,
            # print matching line number and line
            else:
                print(f"{i+1}: {line_stripped}")


def find_file_matches(file_list, regex_pattern, quiet_flag):
    """ Find regex pattern matches in requested files """

    # Iterate through the received file list
    for file in file_list:

        # If file given, isn't a file, exit fatally
        if not os.path.isfile(file):
            sys.exit("ERROR: " + file + " is not a file.")

        # Iterate through the file's lines, print regex-matching ones
        enum_and_match(file, regex_pattern, None, quiet_flag)


def main():
    """ Main function """

    args = parse_cmd_args()

    # Check if received regex pattern is valid
    if not is_valid_regex(args.PATTERN):
        sys.exit("ERROR: regex pattern " + args.PATTERN + " is invalid!")

    # If args.FILE is an empty list, will parse entries from stdin
    if not args.FILE:

        print("Enter your text below:")

        # Read stdin input as list variable
        stdin_ln_list = sys.stdin.readlines()

        # Adding for better readability
        print("")

        # Find matches
        enum_and_match(None, args.PATTERN, stdin_ln_list, args.quiet)

    # Else, file arguments were given, so parse them for regex matches
    else:
        find_file_matches(args.FILE, args.PATTERN, args.quiet)


# If the script is run directly, it will be the main program
if __name__ == "__main__":
    main()
